const REG_NEW_ACCOUNT = 'REG_NEW_ACCOUNT';
const SET_STATE_OF_POPUPS = 'SET_STATE_OF_POPUPS';
const LOGOUT = 'LOGOUT';
const SET_STATE_OF_ACCOUNT = 'SET_STATE_OF_ACCOUNT';

export { REG_NEW_ACCOUNT, SET_STATE_OF_POPUPS, LOGOUT, SET_STATE_OF_ACCOUNT };
